name = "miaoli_bot"
version = "0.10.0"
main = "main.py"
author = "超·乃依"
description = "提供LLM接入QQ对话服务"
entry_class = "MiaoLiBot"
pip_dependencies = { ncatbot5 = ">=5.5.8", langgraph = ">=1.2.12", langchain-core = ">=1.6.5", langchain-openai = ">=1.6.6", langgraph-checkpoint-sqlite = ">=3.1.1", langgraph-checkpoint-postgres = ">=3.1.2", aiosqlite = ">=0.22.1", psycopg = ">=3.3.6", psycopg-pool = ">=3.3.3", aiofiles = ">=24.1.0", pydantic = ">=2.13.5", pyyaml = ">=6.0.3", filetype = ">=1.2.0" }

[dependencies]
