EVENT_PARSER		= "miaoli_bot/chains.event_parser"
SEGMENT_PARSER		= "miaoli_bot/chains.segment_parser"
NCATBOT_API			= "miaoli_bot/ncatbot.api"
RAW_CONFIG			= "miaoli_bot/ncatbot.plugin.config"
PLUGIN_CONFIG		= "miaoli_bot/models.plugin_config"
TOOL_BACKEND		= "miaoli_bot/pi_bridge.pi_tool_backend"
PI_SESSION_MANAGER	= "miaoli_bot/core.pi_session_manager"